trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

steps:
- bash: cd $(System.DefaultWorkingDirectory)/Cake && ./run-build.sh
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'cobertura'
    summaryFileLocation: $(System.DefaultWorkingDirectory)/**/coverage-results/results-*.cobertura.xml