trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: $(System.DefaultWorkingDirectory)/Cake/run-build.sh
- task: PublishCodeCoverageResults@2
  inputs:
    codeCoverageTool: 'cobertura'
    summaryFileLocation: $(System.DefaultWorkingDirectory)/**/coverage-results/results-*.cobertura.xml